esphome:
  name: vacuumgarage
  friendly_name: vacuumgarage

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:


ota:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  manual_ip:
    static_ip: 192.168.10.7
    gateway: 192.168.10.1
    subnet: 255.255.255.0
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Vacuumgarage Fallback Hotspot"
    password: "sHb6gADchew4"

captive_portal:

globals:
  - id: performing_last_movement
    type: boolean
    restore_value: no
    initial_value: 'false'

cover:
  - platform: template
    name: "Vacuum Garage Door"
    id: stepper_motor
    device_class: garage
    open_action:
      - stepper.report_position:
          id: my_stepper
          position: 0
      - stepper.set_target:
          id: my_stepper
          target: 900
    close_action:
      - stepper.report_position:
          id: my_stepper
          position: 0
      - stepper.set_target:
          id: my_stepper
          target: -900
    stop_action:
      - stepper.report_position:
          id: my_stepper
          position: 0
      - stepper.set_target:
          id: my_stepper
          target: 0



binary_sensor:
  - platform: gpio
    pin:
      number: D7
      mode:
        input: true
        pullup: true
    filters:
      - invert:
    name: "Garage Door Open"
    id: open_endstop_binary_sensor
    on_press:
        - stepper.report_position:
            id: my_stepper
            position: 0
        - stepper.set_target:
            id: my_stepper
            target: 0

  - platform: gpio
    pin:
      number: D6
      mode:
        input: true
        pullup: true
    filters:
      - invert:
    name: "Garage Door Closed"
    id: close_endstop_binary_sensor
    on_press:
        - stepper.report_position:
            id: my_stepper
            position: 0
        - stepper.set_target:
            id: my_stepper
            target: 0

  - platform: gpio  #Working. Connect to main ground.
    pin:
      number: D5
      mode:
        input: true
        pullup: true
    name: "Garage Door Vacuum"
    device_class: door
    on_press: #Close door
        - stepper.set_target:
            id: my_stepper
            target: -900
        - delay: 500ms
    on_release: #Open Door
        - stepper.set_target:
            id: my_stepper
            target: 900
        - delay: 500ms


stepper:
  - platform: a4988
    id: my_stepper
    step_pin: D2
    dir_pin: 
      number: D4
      inverted: true
    max_speed: 250 steps/s

    # Optional:
    acceleration: inf
    deceleration: inf


  



  #Additional sensor for pressure sensor? Parked / Not Parked. Or not, is available from Dock. But can be used for potential status light.

  #Light strip thoughts:
    #Not HA: Multiple led sequence when opening and closing. 1 led blinking while vacuum not docked.
    #HA: Above, plus status from HA: Red blinking if error. Other color blinking if need of emptying. Other color if currently active.
